from decouple import config

ONCALL_PROTOCOL = config("ONCALL_PROTOCOL")
ONCALL_HOST = config("ONCALL_HOST")
ONCALL_PORT = int(config("ONCALL_PORT"))
ADMIN_USERNAME = config("ADMIN_USERNAME")
ADMIN_PASSWORD = config("ADMIN_PASSWORD")
YAML_FILE_NAME = config("YAML_FILE_NAME")
LOGFILE = config("LOGFILE")
DUTY_DURATION_HOURS = int(config("DUTY_DURATION_HOURS"))
DUTY_PRIMARY_START_HOUR = int(config("DUTY_PRIMARY_START_HOUR"))
DUTY_SECONDARY_START_HOUR = int(config("DUTY_SECONDARY_START_HOUR"))
